#!/usr/bin/env python3
"""Render a TRD section from plan.json (single source of truth).

Today this renders §10 Milestones from `plan.json` `milestones[]`. The same
seam will fan out to §5 Functional Requirements, §7 High-Level Design, and
§11 APIs Involved as we close the other TRD↔sidecar drift gaps.

Why this exists
---------------
Before this script, `/plan` wrote `trd.md` §10 by re-generating prose from
the same intent that produced `plan.json` `milestones[]`. Both lived as
independent stores with no validator binding them. Drift was silent.

After this script, the sidecar is the structured source-of-truth and §10
is *rendered* from it — the body between `BEGIN_MARKER` and `END_MARKER`
in the live TRD is exactly what `render_section_with_markers()` produces.
`validate_trd.py` enforces that equality (`milestone_drift` named error).

Run via uv (no global pip):

    uv run shield/scripts/render_trd_section.py milestones <plan.json>

Prints the marker-wrapped section to stdout. /plan injects this verbatim
into `trd.md` §10.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# Delimiters that bound the rendered §10 body inside trd.md. Both
# validate_trd.py and the /plan skill MUST use these exact strings;
# changing them is a breaking change for any TRD already on disk.
BEGIN_MARKER = (
    "<!-- BEGIN rendered:milestones — do not edit, "
    "regenerated by /plan from plan.json -->"
)
END_MARKER = "<!-- END rendered:milestones -->"


_ID_NUM_RE = re.compile(r"^M(\d+)$")


def _milestone_num(mid: str) -> int:
    """Numeric component of an ``M<n>`` id. Malformed ids sort last via a
    large sentinel so ordering stays total and deterministic."""
    m = _ID_NUM_RE.match(mid or "")
    return int(m.group(1)) if m else 1_000_000


def _order_milestones(milestones: list[dict]) -> list[dict]:
    """Dependency-topological order, ties broken by numeric id.

    A milestone is emitted only after every id in its ``depends_on`` is
    already emitted. Among ready milestones, the lowest numeric id wins.
    Unknown deps are ignored; an unbreakable cycle falls back to numeric
    order for the remaining nodes so this never loops forever.
    """
    by_id = {m["id"]: m for m in milestones}
    remaining = sorted(milestones, key=lambda m: (_milestone_num(m["id"]), m["id"]))
    emitted: list[dict] = []
    emitted_ids: set[str] = set()
    while remaining:
        progressed = False
        for ms in list(remaining):
            deps = [d for d in (ms.get("depends_on") or []) if d in by_id]
            if all(d in emitted_ids for d in deps):
                emitted.append(ms)
                emitted_ids.add(ms["id"])
                remaining.remove(ms)
                progressed = True
        if not progressed:  # cycle / unsatisfiable — emit rest in numeric order
            emitted.extend(remaining)
            break
    return emitted


def render_milestones(milestones: list[dict]) -> str:
    """Render `plan.json` `milestones[]` as the §10 body block.

    The output is the body *between* the BEGIN/END markers, exclusive of
    the marker lines themselves. Use `render_section_with_markers()` to
    get the marker-wrapped form ready to inject into a TRD.

    Determinism: milestones are ordered dependency-topologically (a milestone
    appears only after everything in its ``depends_on``), ties broken by the
    numeric component of the id. This keeps M10+ in build order rather than
    lexical order.

    Empty `milestones[]` produces a single italic line noting the opt-out
    so the rendered region is never literally empty — that keeps the
    validator's byte-range compare unambiguous.
    """
    if not milestones:
        return "_No milestones — sidecar opts out of milestone tracking._"

    blocks: list[str] = []
    for ms in _order_milestones(milestones):
        deps = ms.get("depends_on") or []
        deps_str = "no deps" if not deps else "deps " + ", ".join(deps)
        outcome = (ms.get("outcome") or "").strip()
        description = (ms.get("description") or "").strip()
        exit_criteria = [ec.strip() for ec in (ms.get("exit_criteria") or [])]
        touches = [c.strip() for c in (ms.get("touches_lld") or []) if c and c.strip()]

        lines = [
            f"### {ms['id']} — {ms['name']}  *({deps_str})*",
            "",
            f"**Outcome:** {outcome}",
        ]
        if description:
            lines += ["", f"**Description:** {description}"]
        if exit_criteria:
            lines += ["", "**Exit criteria:**"]
            lines += [f"- {ec}" for ec in exit_criteria]
        if touches:
            links = ", ".join(f"[`{c}`](lld-{c}.md)" for c in touches)
            lines += ["", f"**Detailed design:** {links}"]
        blocks.append("\n".join(lines))

    # Blank line between milestone blocks keeps markdown rendering crisp.
    return "\n\n".join(blocks)


def render_section_with_markers(milestones: list[dict]) -> str:
    """Full marker-wrapped section — what /plan injects into trd.md §10."""
    return f"{BEGIN_MARKER}\n\n{render_milestones(milestones)}\n\n{END_MARKER}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Render a TRD section from plan.json (one source of truth).",
    )
    parser.add_argument(
        "section",
        choices=["milestones"],
        help=(
            "Which TRD section to render. Only `milestones` is supported today; "
            "this script is the seam for §5/§7/§11 renders in future work."
        ),
    )
    parser.add_argument("plan_json", type=Path, help="Path to plan.json")
    args = parser.parse_args(argv)

    plan = json.loads(args.plan_json.read_text())
    if args.section == "milestones":
        print(render_section_with_markers(plan.get("milestones") or []))
    return 0


if __name__ == "__main__":
    sys.exit(main())
