"""shield/scripts/run_lld_docs.py — CLI wrapper for the lld-docs skill.

Usage:
  python run_lld_docs.py --component <name> --type backend|infra \\
      --mode draft|merge|remerge --target <path> [--context-json <path>]

Emits an LLD file at <target> by reading the appropriate template from
shield/skills/general/lld-docs/lld-template-<type>.md and the slug allow-list
from shield/schema/lld-sections-<type>.yaml. Atomic write via .tmp → rename.

This wrapper is the executable form of the lld-docs SKILL.md contract — the
skill prose is the spec; this script is the testable implementation invoked by
the eval runner.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import date
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_DIR = REPO_ROOT / "shield" / "schema"
TEMPLATE_DIR = REPO_ROOT / "shield" / "skills" / "general" / "lld-docs"


def _load_schema(template_type: str) -> dict:
    return yaml.safe_load((SCHEMA_DIR / f"lld-sections-{template_type}.yaml").read_text())


def _load_marketplace_version() -> str:
    mp = json.loads((REPO_ROOT / ".claude-plugin" / "marketplace.json").read_text())
    for plugin in mp.get("plugins", []):
        if plugin["name"] == "shield":
            return plugin["version"]
    return "0.0.0"


def _build_skeleton(component: str, template_type: str, schema: dict, context: dict) -> str:
    version = _load_marketplace_version()
    today = date.today().isoformat()
    owner = context.get("owner", "unknown@example.com")
    feature = context.get("feature", "manual")
    prd_path = context.get("prd_path", "n/a")
    linked_plans = context.get("linked_plans", [])

    lines = [
        f"<!-- generated by /lld v{version} on {today} -->",
        "",
        f"# LLD — {component}",
        "",
        f"**Feature:** `{feature}`",
        f"**Owner:** {owner}",
        "**Status:** draft",
        f"**Linked PRD:** {prd_path}",
        f"**Linked plans:** {linked_plans}",
        "**Version:** 0.1.0",
        f"**Last updated:** {today}",
        "",
    ]

    for section in schema["sections"]:
        lines.append(f"## §{section['number']} {section['title']} {{#{section['id']}}}")
        lines.append("")
        if section.get("promote_on_demand"):
            lines.append("<details>")
            lines.append(f"<summary>§{section['number']} {section['title']}</summary>")
            lines.append("")
            lines.append("(promote-on-demand — lift by replacing `<details>` with `<details open>`)")
            lines.append("")
            lines.append("</details>")
            lines.append("")
        elif section.get("forced_subsections"):
            for sub in section["forced_subsections"]:
                lines.append(f"### §{sub['number']} {sub['title']} {{#{sub['id']}}}")
                lines.append("")
                lines.append(f"n/a — populate from {context.get('trd_path', 'TRD')} §11 / repo evidence")
                lines.append("")
        else:
            lines.append(f"(populate from {context.get('trd_path', 'TRD')} / PRD)")
            lines.append("")

    # §14 Changelog row
    touch = context.get("touch", "manual")
    story_ids = " ".join(context.get("story_ids", [])) or "n/a"
    summary = context.get("summary", "Initial draft")
    lines.append("")
    lines.append("| Touch | Date | Summary | Story IDs |")
    lines.append("|---|---|---|---|")
    lines.append(f"| {touch} | {today} | {summary} | {story_ids} |")
    lines.append("")

    return "\n".join(lines)


def _atomic_write(target: Path, content: str) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(target.suffix + ".tmp")
    try:
        tmp.write_text(content)
        os.replace(tmp, target)
    except Exception:
        tmp.unlink(missing_ok=True)
        raise


def _detect_conflicting_sections(merged: str) -> list[str]:
    """Scan diff3 output for conflict-marker regions; map each to the §id of the containing section."""
    import re
    sections: list[str] = []
    current_section: str | None = None
    in_conflict = False
    for line in merged.splitlines():
        # Only track top-level (##) sections; ignore sub-section (### …) headers
        # so the conflict report names the canonical §N slug, not a sub-anchor.
        m = re.match(r"##(?!#)\s.*\{#([a-z0-9-]+)\}", line)
        if m:
            current_section = m.group(1)
        if line.startswith("<<<<<<<"):
            in_conflict = True
        elif line.startswith(">>>>>>>"):
            if in_conflict and current_section and current_section not in sections:
                sections.append(current_section)
            in_conflict = False
    return sections


def _remerge(component: str, target: Path, context: dict) -> int:
    """Three-way merge: base = canonical-at-fork, ours = current draft, theirs = canonical-at-promotion."""
    base_path = Path(context["base_path"])
    theirs_path = Path(context["theirs_path"])
    ours_path = target
    result = subprocess.run(
        ["diff3", "-m", str(ours_path), str(base_path), str(theirs_path)],
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        _atomic_write(target, result.stdout)
        print(f"OK — clean merge for {component}")
        return 0
    if result.returncode == 1:
        conflicting_sections = _detect_conflicting_sections(result.stdout)
        print(
            f"CONFLICT — {component}: conflicting sections: {','.join(conflicting_sections)}",
            file=sys.stderr,
        )
        return 1
    print(f"ERROR — diff3 failed: {result.stderr}", file=sys.stderr)
    return 2


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--component", required=True)
    parser.add_argument("--type", required=True, choices=["backend", "infra"])
    parser.add_argument("--mode", required=True, choices=["draft", "merge", "remerge"])
    parser.add_argument("--target", required=True)
    parser.add_argument("--context-json", default=None)
    args = parser.parse_args()

    context: dict = {}
    if args.context_json:
        context = json.loads(Path(args.context_json).read_text())

    schema = _load_schema(args.type)
    target = Path(args.target)

    if args.mode == "draft":
        content = _build_skeleton(args.component, args.type, schema, context)
        _atomic_write(target, content)
    elif args.mode == "merge":
        # Caller has already copied canonical to target; no-op for now.
        pass
    elif args.mode == "remerge":
        return _remerge(args.component, target, context)

    print(f"OK — wrote {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
