"""Tests for the milestone_drift check added to validate_trd.py.

Exercises the new behavior only; existing validator surface (section
presence, anchors, ordering, vague-body) is unchanged and remains covered
in integration by /plan-review's gate 0b.

Run via uv from the repo root:

    uv run shield/scripts/test_validate_trd_drift.py
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "shield" / "scripts" / "validate_trd.py"

sys.path.insert(0, str(Path(__file__).parent))
from render_trd_section import render_section_with_markers  # noqa: E402


PROVENANCE = "<!-- generated by /plan v2.20.0 on 2026-05-28 -->"

# Body for every TRD section EXCEPT §10, in canonical order. §10 is injected
# per-test so we can exercise the drift logic in isolation.
FROZEN_BEFORE_10 = """\
## §1 Document Overview {#document-overview}

Body.

## §2 Problem Statement {#problem-statement}

Body.

## §3 Objective & Scope {#objective-scope}

Body.

## §4 Product Journey {#product-journey}

Body.

## §5 Functional Requirements {#functional-requirements}

Body.

## §6 Non-Functional Requirements {#non-functional-requirements}

Body.

## §7 High-Level Design {#high-level-design}

Body.

## §8 Alternatives Considered {#alternatives-considered}

Body.

## §9 Cross-Cutting Concerns {#cross-cutting-concerns}

Body.
"""

FROZEN_AFTER_10 = """
## §11 APIs Involved {#apis-involved}

Body.

## §12 Open Questions {#open-questions}

Body.

## §13 References {#references}

Body.

## §14 Rollback Strategy {#rollback-strategy}

Body.
"""

MS_M1 = {
    "id": "M1",
    "name": "Capture",
    "outcome": "store ready",
    "exit_criteria": ["validator behaves"],
    "depends_on": [],
}


def _write_trd(tmp_path: Path, milestones_body: str) -> Path:
    """Write a 14-section TRD using milestones_body as the §10 content."""
    trd = tmp_path / "trd.md"
    trd.write_text(
        f"---\ntitle: Test TRD\n---\n{PROVENANCE}\n\n"
        + FROZEN_BEFORE_10
        + "\n## §10 Milestones {#milestones}\n\n"
        + milestones_body
        + "\n"
        + FROZEN_AFTER_10,
    )
    return trd


def _write_plan(tmp_path: Path, milestones: list[dict]) -> Path:
    plan = tmp_path / "plan.json"
    plan.write_text(json.dumps({"milestones": milestones}, indent=2))
    return plan


def _run(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["uv", "run", "--with", "pyyaml", str(SCRIPT), *args],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )


# ───────────────────────── back-compat ─────────────────────────

def test_no_markers_in_s10_skips_drift_check(tmp_path: Path) -> None:
    """Pre-cutover TRDs (hand-written §10, no markers) still validate cleanly.

    This is the safety net so the new check doesn't retroactively break any
    TRD that landed before the §10-render cutover.
    """
    trd = _write_trd(tmp_path, "Hand-written milestone prose here.\n")
    _write_plan(tmp_path, [MS_M1])
    r = _run(str(trd))
    assert r.returncode == 0, f"expected exit 0; stderr={r.stderr}"


# ───────────────────────── drift detection ─────────────────────────

def test_drift_detected_when_body_differs(tmp_path: Path) -> None:
    """Markers present but body differs from render → FAIL milestone_drift."""
    body = (
        "<!-- BEGIN rendered:milestones — do not edit, "
        "regenerated by /plan from plan.json -->\n"
        "\n"
        "### M1 — WRONG NAME  *(no deps)*\n\n"
        "**Outcome:** mismatched\n\n"
        "**Exit criteria:**\n- mismatched\n"
        "\n"
        "<!-- END rendered:milestones -->\n"
    )
    trd = _write_trd(tmp_path, body)
    _write_plan(tmp_path, [MS_M1])
    r = _run(str(trd))
    assert r.returncode == 1, f"expected exit 1; stderr={r.stderr}"
    assert "milestone_drift" in r.stderr


def test_matching_body_passes(tmp_path: Path) -> None:
    """Body matches render_section_with_markers([M1]) → pass."""
    body = render_section_with_markers([MS_M1])
    trd = _write_trd(tmp_path, body)
    _write_plan(tmp_path, [MS_M1])
    r = _run(str(trd))
    assert r.returncode == 0, f"expected exit 0; stderr={r.stderr}"


# ───────────────────────── structural errors ─────────────────────────

def test_unbounded_markers_when_end_missing(tmp_path: Path) -> None:
    body = (
        "<!-- BEGIN rendered:milestones — do not edit, "
        "regenerated by /plan from plan.json -->\n"
        "### M1 — X *(no deps)*\n\n**Outcome:** y\n"
        # NO END marker
    )
    trd = _write_trd(tmp_path, body)
    _write_plan(tmp_path, [MS_M1])
    r = _run(str(trd))
    assert r.returncode == 1
    assert "unbounded_markers:milestones" in r.stderr


def test_missing_sidecar_fails(tmp_path: Path) -> None:
    """Markers present but no plan.json sibling → missing_sidecar."""
    body = render_section_with_markers([MS_M1])
    trd = _write_trd(tmp_path, body)
    # deliberately do not write plan.json
    r = _run(str(trd))
    assert r.returncode == 1
    assert "missing_sidecar" in r.stderr


# ───────────────────────── runner ─────────────────────────

def _runner() -> int:
    import tempfile

    failures: list[str] = []
    tests = sorted(
        (name, fn)
        for name, fn in globals().items()
        if name.startswith("test_") and callable(fn)
    )
    for name, fn in tests:
        with tempfile.TemporaryDirectory() as td:
            try:
                fn(Path(td))
                print(f"  ok   {name}")
            except AssertionError as e:
                failures.append(f"  FAIL {name}: {e}")
                print(failures[-1])
            except Exception as e:  # noqa: BLE001
                failures.append(f"  ERR  {name}: {type(e).__name__}: {e}")
                print(failures[-1])
    print(f"\n{len(failures)} failure(s)" if failures else "\nall green")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(_runner())
