"""Tests for the §7 HLD diagram gate in validate_trd.py."""
from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "shield" / "scripts" / "validate_trd.py"
sys.path.insert(0, str(Path(__file__).parent))
from render_trd_section import render_section_with_markers  # noqa: E402

PROVENANCE = "<!-- generated by /plan v2.26.0 on 2026-06-01 -->"

SECTION_TITLES = [
    ("document-overview", "Document Overview"), ("problem-statement", "Problem Statement"),
    ("objective-scope", "Objective & Scope"), ("product-journey", "Product Journey"),
    ("functional-requirements", "Functional Requirements"),
    ("non-functional-requirements", "Non-Functional Requirements"),
    ("high-level-design", "High-Level Design"), ("alternatives-considered", "Alternatives Considered"),
    ("cross-cutting-concerns", "Cross-Cutting Concerns"), ("milestones", "Milestones"),
    ("apis-involved", "APIs Involved"), ("open-questions", "Open Questions"),
    ("references", "References"), ("rollback-strategy", "Rollback Strategy"),
]


def _trd(s7_body: str) -> str:
    """Build a full 14-section TRD; §7 body is parameterized, §10 uses an empty render."""
    parts = [PROVENANCE, ""]
    for i, (slug, title) in enumerate(SECTION_TITLES, start=1):
        parts.append(f"## §{i} {title} {{#{slug}}}")
        if slug == "high-level-design":
            parts.append(s7_body)
        elif slug == "milestones":
            parts.append(render_section_with_markers([]))
        else:
            parts.append(f"Body for {title}.")
        parts.append("")
    return "\n".join(parts)


def _run(trd_text: str) -> subprocess.CompletedProcess:
    with tempfile.TemporaryDirectory() as d:
        p = Path(d) / "trd.md"
        p.write_text(trd_text)
        return subprocess.run([sys.executable, str(SCRIPT), str(p)],
                              capture_output=True, text=True)


def test_section7_without_mermaid_fails():
    r = _run(_trd("Components: a service and a database. No diagram here."))
    assert r.returncode == 1
    assert "hld_missing_diagram:high-level-design" in r.stderr


def test_section7_with_ascii_boxart_fails():
    body = "```\n┌──────┐\n│ svc  │\n└──────┘\n```"
    r = _run(_trd(body))
    assert r.returncode == 1
    assert "hld_ascii_art:high-level-design" in r.stderr


def test_section7_with_mermaid_passes_hld_checks():
    body = "```mermaid\nflowchart LR\n  User --> Service --> DB[(Store)]\n```"
    r = _run(_trd(body))
    assert "hld_missing_diagram" not in r.stderr
    assert "hld_ascii_art" not in r.stderr
