#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "pyyaml>=6.0",
# ]
# ///
"""validate_trd.py — validate a /plan-emitted trd.md against the 14-section template.

Source of truth for the slug allow-list: shield/schema/trd-sections.yaml.

Exit codes:
  0  — TRD is valid.
  1  — TRD fails validation (named error printed to stderr).
  2  — usage error.

Named errors (stderr prefix on FAIL):
  missing_section:<slug>     — a required section header is absent
  missing_anchor:<slug>      — a header is present but its {#slug} anchor is missing
  out_of_order:<slug>        — section appears in a non-canonical order
  unexpected_section:<text>  — drift-by-addition (a 15th+ section)
  vague_section:<slug>       — section body is "TBD" / "TODO" / "???" / whitespace
  na_missing_reason:<slug>   — `n/a` without the `— <reason>` suffix
  provenance_missing         — no `<!-- generated by /plan v… on … -->` stamp
  milestone_drift            — §10 rendered region differs from render_trd_section.py
                               output for the sibling plan.json (Critical)
  unbounded_markers:<slug>   — BEGIN marker present but END marker missing
  missing_sidecar            — §10 has render markers but plan.json was not found

Usage:
  uv run shield/scripts/validate_trd.py PATH_TO_TRD_MD [--sidecar PATH_TO_PLAN_JSON]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover
    print("validate_trd: requires pyyaml (uv run will install it)", file=sys.stderr)
    sys.exit(2)

# Sibling-import: render_trd_section.py lives next to this file. Adding the
# script dir to sys.path lets us share the single render+markers source so
# the validator's expected output is byte-identical to what /plan emits.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from render_trd_section import (  # noqa: E402
    BEGIN_MARKER as MILESTONE_BEGIN,
    END_MARKER as MILESTONE_END,
    render_milestones,
)

# Slice the bytes BETWEEN the BEGIN/END markers (markers excluded). The body
# captured here is what we compare against render_milestones(plan.json).
_MILESTONE_REGION_RE = re.compile(
    re.escape(MILESTONE_BEGIN) + r"\n*(.*?)\n*" + re.escape(MILESTONE_END),
    re.DOTALL,
)


REPO_ROOT = Path(__file__).resolve().parents[2]
TRD_SECTIONS_PATH = REPO_ROOT / "shield" / "schema" / "trd-sections.yaml"

HEADER_RE = re.compile(r"^##\s+(?:§\s*(\d+)\s+)?(.+?)\s*\{#([a-z0-9-]+)\}\s*$", re.MULTILINE)
BARE_HEADER_RE = re.compile(r"^##\s+(?:§\s*(\d+)\s+)?(.+?)\s*$", re.MULTILINE)
PROVENANCE_RE = re.compile(r"<!--\s*generated by /plan v[\w.\-]+ on \d{4}-\d{2}-\d{2}\s*-->")
NA_RE = re.compile(r"^\s*n/a\b(?:\s*[—-]\s*(.+))?\s*$", re.IGNORECASE)
VAGUE_TOKENS = {"tbd", "todo", "???", "fixme", "n/a"}  # bare "n/a" without reason is vague

ASCII_BOXART_CHARS = set("┌┐└┘├┤┬┴┼│─")


def _has_ascii_boxart(body: str) -> bool:
    return any(c in ASCII_BOXART_CHARS for c in body) or "+--" in body


def _emit(severity: str, code: str, message: str = "") -> None:
    line = f"{severity}: {code}"
    if message:
        line += f": {message}"
    print(line, file=sys.stderr)


def _load_sections() -> list[dict[str, Any]]:
    spec = yaml.safe_load(TRD_SECTIONS_PATH.read_text())
    return list(spec["sections"])


def _section_bodies(text: str, anchor_positions: list[tuple[str, int]]) -> dict[str, str]:
    """Slice the document at each anchored header. Returns slug → body text."""
    bodies: dict[str, str] = {}
    for i, (slug, start) in enumerate(anchor_positions):
        end = anchor_positions[i + 1][1] if i + 1 < len(anchor_positions) else len(text)
        bodies[slug] = text[start:end]
    return bodies


def _classify_body(body: str) -> tuple[str, str | None]:
    """Return (status, reason). status ∈ {ok, vague, na_no_reason, na_ok}."""
    lines = [ln for ln in body.split("\n", 1)[1:][0].splitlines() if ln.strip()] if "\n" in body else []
    if not lines:
        return "vague", None
    # Strip out any trailing/leading whitespace on the body proper.
    content_lines = [ln.strip() for ln in lines if ln.strip()]
    if not content_lines:
        return "vague", None
    # Single-line n/a — <reason> check.
    if len(content_lines) == 1:
        m = NA_RE.match(content_lines[0])
        if m:
            return ("na_ok", m.group(1).strip()) if m.group(1) else ("na_no_reason", None)
    # Body contains only vague tokens?
    if all(ln.strip().lower().strip(".") in VAGUE_TOKENS for ln in content_lines):
        return "vague", None
    return "ok", None


def _check_milestone_drift(
    milestones_body: str | None,
    sidecar_path: Path | None,
) -> bool:
    """Compare the live §10 rendered region against render_milestones(plan.json).

    Returns True on FAIL. Returns False (no-op) when §10 has no BEGIN marker —
    that's the back-compat path for any TRD authored before the §10-render
    cutover. Once a TRD opts in by emitting BEGIN, the END marker becomes
    mandatory and the sibling sidecar becomes mandatory.

    Named errors raised here:
      unbounded_markers:milestones  — BEGIN without END (or unsliceable region)
      missing_sidecar               — markers present but plan.json not found
      milestone_drift               — body differs from the renderer's output
    """
    if milestones_body is None:
        # §10 missing entirely — that's `missing_section:milestones`, already
        # reported by the presence check; don't double-emit here.
        return False

    if MILESTONE_BEGIN not in milestones_body:
        return False  # back-compat: pre-cutover TRD, no drift check

    if MILESTONE_END not in milestones_body:
        _emit("FAIL", "unbounded_markers:milestones",
              "BEGIN marker present but END marker missing")
        return True

    if sidecar_path is None or not sidecar_path.is_file():
        _emit("FAIL", "missing_sidecar",
              str(sidecar_path) if sidecar_path else "no plan.json sibling found")
        return True

    try:
        plan = json.loads(sidecar_path.read_text())
    except json.JSONDecodeError as e:
        _emit("FAIL", "missing_sidecar", f"plan.json is not valid JSON: {e}")
        return True

    expected = render_milestones(plan.get("milestones") or [])
    match = _MILESTONE_REGION_RE.search(milestones_body)
    if not match:
        # Defensive: both markers found but the regex couldn't slice the body
        # (e.g. markers in unexpected order). Structural error.
        _emit("FAIL", "unbounded_markers:milestones",
              "BEGIN/END markers found but region could not be sliced")
        return True

    actual = match.group(1).strip("\n").strip()
    if actual != expected.strip():
        _emit("FAIL", "milestone_drift",
              "§10 rendered region does not match render_trd_section.py "
              "output for the sidecar; re-run /plan to refresh.")
        return True
    return False


def validate(trd_path: Path, sidecar_path: Path | None = None) -> int:
    if not trd_path.is_file():
        _emit("FAIL", "file_not_found", str(trd_path))
        return 2
    text = trd_path.read_text()
    sections = _load_sections()
    expected_slugs = [s["id"] for s in sections]

    fail = False

    # Provenance stamp.
    if not PROVENANCE_RE.search(text):
        _emit("FAIL", "provenance_missing")
        fail = True

    # Anchored headers — collect position + slug.
    anchored: list[tuple[str, int]] = [(m.group(3), m.start()) for m in HEADER_RE.finditer(text)]
    anchored_slugs = [a[0] for a in anchored]

    # Bare headers (no anchor) — used to detect missing-anchor + drift.
    bare_headers: list[tuple[str, int]] = []
    for m in BARE_HEADER_RE.finditer(text):
        line = m.group(0)
        if "{#" in line:
            continue
        title = m.group(2).strip()
        bare_headers.append((title, m.start()))

    # Map slugs in canonical order; detect missing.
    expected_set = set(expected_slugs)
    present_set = set(anchored_slugs)
    missing = [s for s in expected_slugs if s not in present_set]
    for slug in missing:
        # Check if there is a bare header matching the canonical title — that's
        # a missing-anchor, not a missing-section.
        title = next(sec["title"] for sec in sections if sec["id"] == slug)
        if any(t.lower() == title.lower() for t, _ in bare_headers):
            _emit("FAIL", f"missing_anchor:{slug}")
        else:
            _emit("FAIL", f"missing_section:{slug}")
        fail = True

    # Unexpected sections (drift-by-addition). Anchored slugs outside the allow-list
    # OR bare headers that don't match a canonical title.
    extra_anchored = [s for s in anchored_slugs if s not in expected_set]
    for s in extra_anchored:
        _emit("FAIL", f"unexpected_section:{s}")
        fail = True
    canonical_titles_lc = {sec["title"].lower() for sec in sections}
    for title, _ in bare_headers:
        if title.lower() not in canonical_titles_lc:
            _emit("FAIL", f"unexpected_section:{title}")
            fail = True

    # Out-of-order check. Anchored slugs that are in the allow-list must appear in
    # canonical order.
    in_allow = [s for s in anchored_slugs if s in expected_set]
    canonical_index = {s: i for i, s in enumerate(expected_slugs)}
    last_idx = -1
    for s in in_allow:
        idx = canonical_index[s]
        if idx < last_idx:
            _emit("FAIL", f"out_of_order:{s}")
            fail = True
        last_idx = max(last_idx, idx)

    # Body content checks.
    bodies = _section_bodies(text, anchored)
    for slug, body in bodies.items():
        if slug not in expected_set:
            continue
        status, _reason = _classify_body(body)
        if status == "vague":
            _emit("FAIL", f"vague_section:{slug}")
            fail = True
        elif status == "na_no_reason":
            _emit("FAIL", f"na_missing_reason:{slug}")
            fail = True

    # §7 High-Level Design must carry at least one Mermaid diagram, never ASCII art.
    hld_body = bodies.get("high-level-design")
    if hld_body is not None:
        if "```mermaid" not in hld_body.lower():
            _emit("FAIL", "hld_missing_diagram:high-level-design",
                  "§7 must contain at least one ```mermaid diagram")
            fail = True
        if _has_ascii_boxart(hld_body):
            _emit("FAIL", "hld_ascii_art:high-level-design",
                  "§7 contains ASCII box-art; diagrams must be Mermaid")
            fail = True

    # §10 single-source-of-truth check: the rendered region inside §10 must
    # match render_milestones(plan.json). Sidecar defaults to {trd_dir}/plan.json
    # when --sidecar was not passed on the CLI.
    effective_sidecar = sidecar_path or (trd_path.parent / "plan.json")
    if _check_milestone_drift(bodies.get("milestones"), effective_sidecar):
        fail = True

    return 1 if fail else 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("trd_md", help="Path to a /plan-emitted trd.md")
    parser.add_argument(
        "--sidecar",
        type=Path,
        default=None,
        help="Path to plan.json. Defaults to {trd_dir}/plan.json when omitted.",
    )
    args = parser.parse_args(argv)
    return validate(Path(args.trd_md), sidecar_path=args.sidecar)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
