name: CI

on:
  pull_request:
    branches: [main]
    paths: ["src/**", "tests/**"]
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.5"
      - run: terraform -chdir=src fmt -check
      - run: terraform -chdir=src init -backend=false
      - run: terraform -chdir=src validate

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bridgecrewio/checkov-action@v12
        with:
          directory: src/
          quiet: true
          soft_fail: true

  test:
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.5"
      - run: terraform -chdir=src init -backend=false
      - run: terraform -chdir=src test
